param(
  [string]$SkillsDir = 'skills',
  [switch]$DryRun
)

$root = Split-Path -Parent $PSScriptRoot
$src = Join-Path $root $SkillsDir

$map = @{}
$map['windows-desktop-e2e'] = 'platform-specific\windows'
$map['android-clean-architecture'] = 'platform-specific\android'
$map['ios-icon-gen'] = 'platform-specific\ios'
$map['swift-actor-persistence'] = 'platform-specific\ios'
$map['swift-concurrency-6-2'] = 'platform-specific\ios'
$map['swift-protocol-di-testing'] = 'platform-specific\ios'
$map['swiftui-patterns'] = 'platform-specific\ios'
$map['flutter-dart-code-review'] = 'platform-specific\flutter'
$map['react-native-patterns'] = 'platform-specific\react-native'
$map['bun-runtime'] = 'platform-specific\bun'
$map['flox-environments'] = 'platform-specific\flox'

$map['react-patterns'] = 'framework-specific\react'
$map['react-performance'] = 'framework-specific\react'
$map['react-testing'] = 'framework-specific\react'
$map['vue-patterns'] = 'framework-specific\vue'
$map['angular-developer'] = 'framework-specific\angular'
$map['nextjs-turbopack'] = 'framework-specific\nextjs'
$map['nuxt4-patterns'] = 'framework-specific\nuxt'
$map['vite-patterns'] = 'framework-specific\vite'
$map['django-patterns'] = 'framework-specific\django'
$map['django-celery'] = 'framework-specific\django'
$map['django-security'] = 'framework-specific\django'
$map['django-tdd'] = 'framework-specific\django'
$map['django-verification'] = 'framework-specific\django'
$map['laravel-patterns'] = 'framework-specific\laravel'
$map['laravel-security'] = 'framework-specific\laravel'
$map['laravel-tdd'] = 'framework-specific\laravel'
$map['laravel-verification'] = 'framework-specific\laravel'
$map['laravel-plugin-discovery'] = 'framework-specific\laravel'
$map['springboot-patterns'] = 'framework-specific\spring-boot'
$map['springboot-security'] = 'framework-specific\spring-boot'
$map['springboot-tdd'] = 'framework-specific\spring-boot'
$map['springboot-verification'] = 'framework-specific\spring-boot'
$map['quarkus-patterns'] = 'framework-specific\quarkus'
$map['quarkus-security'] = 'framework-specific\quarkus'
$map['quarkus-tdd'] = 'framework-specific\quarkus'
$map['quarkus-verification'] = 'framework-specific\quarkus'
$map['nestjs-patterns'] = 'framework-specific\nestjs'
$map['fastapi-patterns'] = 'framework-specific\fastapi'
$map['compose-multiplatform-patterns'] = 'framework-specific\compose-multiplatform'

$map['agent-architecture-audit'] = 'function-specific\ai-agent'
$map['agent-eval'] = 'function-specific\ai-agent'
$map['agent-harness-construction'] = 'function-specific\ai-agent'
$map['agent-introspection-debugging'] = 'function-specific\ai-agent'
$map['agent-payment-x402'] = 'function-specific\ai-agent'
$map['agent-self-evaluation'] = 'function-specific\ai-agent'
$map['agent-sort'] = 'function-specific\ai-agent'
$map['agentic-engineering'] = 'function-specific\ai-agent'
$map['agentic-os'] = 'function-specific\ai-agent'
$map['ai-first-engineering'] = 'function-specific\ai-agent'
$map['ai-regression-testing'] = 'function-specific\ai-agent'
$map['autonomous-agent-harness'] = 'function-specific\ai-agent'
$map['autonomous-loops'] = 'function-specific\ai-agent'
$map['eval-harness'] = 'function-specific\ai-agent'
$map['gan-style-harness'] = 'function-specific\ai-agent'
$map['cost-tracking'] = 'function-specific\ai-agent'
$map['parallel-execution-optimizer'] = 'function-specific\ai-agent'
$map['team-agent-orchestration'] = 'function-specific\ai-agent'
$map['team-builder'] = 'function-specific\ai-agent'
$map['dmux-workflows'] = 'function-specific\ai-agent'
$map['ralphinho-rfc-pipeline'] = 'function-specific\ai-agent'
$map['using-superpowers'] = 'function-specific\ai-agent'
$map['dispatching-parallel-agents'] = 'function-specific\ai-agent'

$map['kubernetes'] = 'function-specific\devops'
$map['kubernetes-patterns'] = 'function-specific\devops'
$map['kubernetes-specialist'] = 'function-specific\devops'
$map['docker-patterns'] = 'function-specific\devops'
$map['terraform-engineer'] = 'function-specific\devops'
$map['sre-engineer'] = 'function-specific\devops'
$map['monitoring-expert'] = 'function-specific\devops'
$map['chaos-engineer'] = 'function-specific\devops'
$map['netmiko-ssh-automation'] = 'function-specific\devops'
$map['network-bgp-diagnostics'] = 'function-specific\devops'
$map['network-config-validation'] = 'function-specific\devops'
$map['network-interface-health'] = 'function-specific\devops'
$map['homelab-network-readiness'] = 'function-specific\devops'
$map['homelab-network-setup'] = 'function-specific\devops'
$map['homelab-pihole-dns'] = 'function-specific\devops'
$map['homelab-vlan-segmentation'] = 'function-specific\devops'
$map['homelab-wireguard-vpn'] = 'function-specific\devops'
$map['cisco-ios-patterns'] = 'function-specific\devops'
$map['deployment-patterns'] = 'function-specific\devops'
$map['uncloud'] = 'function-specific\devops'
$map['generating-python-installer'] = 'function-specific\devops'
$map['nanoclaw-repl'] = 'function-specific\devops'
$map['embedded-systems'] = 'function-specific\devops'

$map['postgresql'] = 'function-specific\database'
$map['postgres-patterns'] = 'function-specific\database'
$map['mysql'] = 'function-specific\database'
$map['mysql-patterns'] = 'function-specific\database'
$map['oracle-sql'] = 'function-specific\database'
$map['sql-review'] = 'function-specific\database'
$map['database-migrations'] = 'function-specific\database'
$map['clickhouse-io'] = 'function-specific\database'
$map['prisma-patterns'] = 'function-specific\database'
$map['jpa-patterns'] = 'function-specific\database'
$map['kotlin-exposed-patterns'] = 'function-specific\database'

$map['backend-patterns'] = 'function-specific\backend'
$map['api-design'] = 'function-specific\backend'
$map['api-connector-builder'] = 'function-specific\backend'
$map['dotnet-patterns'] = 'function-specific\backend'
$map['golang-patterns'] = 'function-specific\backend'
$map['golang-testing'] = 'function-specific\backend'
$map['nodejs-keccak256'] = 'function-specific\backend'
$map['tinystruct-patterns'] = 'function-specific\backend'

$map['frontend-patterns'] = 'function-specific\frontend'
$map['frontend-a11y'] = 'function-specific\frontend'
$map['frontend-design-direction'] = 'function-specific\frontend'
$map['frontend-slides'] = 'function-specific\frontend'
$map['accessibility'] = 'function-specific\frontend'
$map['make-interfaces-feel-better'] = 'function-specific\frontend'
$map['browser-act'] = 'function-specific\frontend'
$map['browser-qa'] = 'function-specific\frontend'
$map['browser-use'] = 'function-specific\frontend'
$map['ui-demo'] = 'function-specific\frontend'
$map['ui-to-vue'] = 'function-specific\frontend'
$map['motion-advanced'] = 'function-specific\frontend'
$map['motion-foundations'] = 'function-specific\frontend'
$map['motion-patterns'] = 'function-specific\frontend'
$map['motion-ui'] = 'function-specific\frontend'
$map['design-system'] = 'function-specific\frontend'
$map['brand-discovery'] = 'function-specific\frontend'
$map['brand-voice'] = 'function-specific\frontend'
$map['liquid-glass-design'] = 'function-specific\frontend'

$map['cpp-testing'] = 'function-specific\testing'
$map['cpp-coding-standards'] = 'function-specific\testing'
$map['csharp-testing'] = 'function-specific\testing'
$map['python-patterns'] = 'function-specific\testing'
$map['python-testing'] = 'function-specific\testing'
$map['pytorch-patterns'] = 'function-specific\testing'
$map['java-coding-standards'] = 'function-specific\testing'
$map['kotlin-coroutines-flows'] = 'function-specific\testing'
$map['kotlin-ktor-patterns'] = 'function-specific\testing'
$map['kotlin-patterns'] = 'function-specific\testing'
$map['kotlin-testing'] = 'function-specific\testing'
$map['perl-patterns'] = 'function-specific\testing'
$map['perl-security'] = 'function-specific\testing'
$map['perl-testing'] = 'function-specific\testing'
$map['fsharp-testing'] = 'function-specific\testing'
$map['rust-patterns'] = 'function-specific\testing'
$map['rust-testing'] = 'function-specific\testing'
$map['e2e-testing'] = 'function-specific\testing'
$map['healthcare-eval-harness'] = 'function-specific\testing'
$map['benchmark'] = 'function-specific\testing'
$map['benchmark-optimization-loop'] = 'function-specific\testing'
$map['benchmark-methodology'] = 'function-specific\testing'

$map['security-reviewer'] = 'function-specific\security'
$map['security-review'] = 'function-specific\security'
$map['security-scan'] = 'function-specific\security'
$map['security-bounty-hunter'] = 'function-specific\security'
$map['llm-trading-agent-security'] = 'function-specific\security'
$map['defi-amm-security'] = 'function-specific\security'
$map['hipaa-compliance'] = 'function-specific\security'
$map['healthcare-phi-compliance'] = 'function-specific\security'

$map['dashboard-builder'] = 'function-specific\monitoring'
$map['canary-watch'] = 'function-specific\monitoring'

$map['article-writing'] = 'function-specific\content'
$map['content-engine'] = 'function-specific\content'
$map['video-editing'] = 'function-specific\content'
$map['remotion-video-creation'] = 'function-specific\content'
$map['social-publisher'] = 'function-specific\content'
$map['crosspost'] = 'function-specific\content'
$map['manim-video'] = 'function-specific\content'
$map['taste'] = 'function-specific\content'
$map['investor-materials'] = 'function-specific\content'
$map['investor-outreach'] = 'function-specific\content'
$map['marketing-campaign'] = 'function-specific\content'
$map['seo'] = 'function-specific\content'

$map['carrier-relationship-management'] = 'function-specific\business'
$map['customer-billing-ops'] = 'function-specific\business'
$map['finance-billing-ops'] = 'function-specific\business'
$map['logistics-exception-management'] = 'function-specific\business'
$map['returns-reverse-logistics'] = 'function-specific\business'
$map['inventory-demand-planning'] = 'function-specific\business'
$map['production-scheduling'] = 'function-specific\business'
$map['quality-nonconformance'] = 'function-specific\business'
$map['energy-procurement'] = 'function-specific\business'
$map['customs-trade-compliance'] = 'function-specific\business'
$map['lead-intelligence'] = 'function-specific\business'
$map['market-research'] = 'function-specific\business'
$map['data-scraper-agent'] = 'function-specific\business'
$map['ito-basket-compare'] = 'function-specific\business'
$map['ito-data-atlas-agent'] = 'function-specific\business'
$map['ito-market-intelligence'] = 'function-specific\business'
$map['ito-trade-planner'] = 'function-specific\business'
$map['prediction-market-oracle-research'] = 'function-specific\business'
$map['prediction-market-risk-review'] = 'function-specific\business'
$map['growth-log'] = 'function-specific\business'
$map['cost-aware-llm-pipeline'] = 'function-specific\business'
$map['evm-token-decimals'] = 'function-specific\business'

$map['deep-research'] = 'function-specific\research'
$map['research-ops'] = 'function-specific\research'
$map['scientific-db-pubmed-database'] = 'function-specific\research'
$map['scientific-db-uspto-database'] = 'function-specific\research'
$map['scientific-pkg-gget'] = 'function-specific\research'
$map['scientific-thinking-literature-review'] = 'function-specific\research'
$map['scientific-thinking-scholar-evaluation'] = 'function-specific\research'
$map['pubmed-database'] = 'function-specific\research'
$map['uspto-database'] = 'function-specific\research'
$map['literature-review'] = 'function-specific\research'
$map['scholar-evaluation'] = 'function-specific\research'

$map['composio'] = 'function-specific\integration'
$map['firecrawl'] = 'function-specific\integration'
$map['anysearch'] = 'function-specific\integration'
$map['exa-search'] = 'function-specific\integration'
$map['mcp-server-patterns'] = 'function-specific\integration'
$map['jira-integration'] = 'function-specific\integration'
$map['google-workspace-ops'] = 'function-specific\integration'
$map['email-ops'] = 'function-specific\integration'
$map['messages-ops'] = 'function-specific\integration'
$map['unified-notifications-ops'] = 'function-specific\integration'
$map['project-flow-ops'] = 'function-specific\integration'
$map['github-ops'] = 'function-specific\integration'
$map['x-api'] = 'function-specific\integration'
$map['nutrient-document-processing'] = 'function-specific\integration'
$map['videodb'] = 'function-specific\integration'
$map['mailtrap-email-integration'] = 'function-specific\integration'

$map['cloud-architect'] = 'function-specific\cloud'
$map['homelab-network-setup'] = 'function-specific\cloud'
$map['homelab-pihole-dns'] = 'function-specific\cloud'
$map['homelab-vlan-segmentation'] = 'function-specific\cloud'
$map['homelab-wireguard-vpn'] = 'function-specific\cloud'

$map['data-throughput-accelerator'] = 'function-specific\data'
$map['clickhouse-io'] = 'function-specific\data'
$map['recsys-pipeline-architect'] = 'function-specific\data'

$map['brainstorming'] = 'function-specific\development-workflow'
$map['writing-plans'] = 'function-specific\development-workflow'
$map['executing-plans'] = 'function-specific\development-workflow'
$map['test-driven-development'] = 'function-specific\development-workflow'
$map['systematic-debugging'] = 'function-specific\development-workflow'
$map['subagent-driven-development'] = 'function-specific\development-workflow'
$map['receiving-code-review'] = 'function-specific\development-workflow'
$map['requesting-code-review'] = 'function-specific\development-workflow'
$map['verification-before-completion'] = 'function-specific\development-workflow'
$map['using-git-worktrees'] = 'function-specific\development-workflow'
$map['finishing-a-development-branch'] = 'function-specific\development-workflow'
$map['blueprint'] = 'function-specific\development-workflow'
$map['plan-canvas'] = 'function-specific\development-workflow'
$map['plan-orchestrate'] = 'function-specific\development-workflow'
$map['product-capability'] = 'function-specific\development-workflow'
$map['product-lens'] = 'function-specific\development-workflow'
$map['intent-driven-development'] = 'function-specific\development-workflow'
$map['verification-loop'] = 'function-specific\development-workflow'
$map['search-first'] = 'function-specific\development-workflow'
$map['delivery-gate'] = 'function-specific\development-workflow'
$map['plankton-code-quality'] = 'function-specific\development-workflow'
$map['codehealth-mcp'] = 'function-specific\development-workflow'
$map['rules-distill'] = 'function-specific\development-workflow'
$map['prompt-optimizer'] = 'function-specific\development-workflow'
$map['token-budget-advisor'] = 'function-specific\development-workflow'
$map['continuous-learning-v2'] = 'function-specific\development-workflow'
$map['continuous-agent-loop'] = 'function-specific\development-workflow'
$map['continuous-learning'] = 'function-specific\development-workflow'
$map['iterative-retrieval'] = 'function-specific\development-workflow'
$map['strategic-compact'] = 'function-specific\development-workflow'
$map['hookify-rules'] = 'function-specific\development-workflow'
$map['ai-safety-sop'] = 'function-specific\development-workflow'
$map['config-gc'] = 'function-specific\development-workflow'
$map['context-budget'] = 'function-specific\development-workflow'

$map['coding-standards'] = 'function-specific\language-ecosystem'
$map['python-patterns'] = 'function-specific\language-ecosystem'
$map['python-testing'] = 'function-specific\language-ecosystem'
$map['java-coding-standards'] = 'function-specific\language-ecosystem'
$map['cpp-coding-standards'] = 'function-specific\language-ecosystem'
$map['csharp-testing'] = 'function-specific\language-ecosystem'
$map['golang-patterns'] = 'function-specific\language-ecosystem'
$map['golang-testing'] = 'function-specific\language-ecosystem'
$map['rust-patterns'] = 'function-specific\language-ecosystem'
$map['rust-testing'] = 'function-specific\language-ecosystem'
$map['swift-concurrency-6-2'] = 'function-specific\language-ecosystem'
$map['swift-actor-persistence'] = 'function-specific\language-ecosystem'
$map['swift-protocol-di-testing'] = 'function-specific\language-ecosystem'
$map['swiftui-patterns'] = 'function-specific\language-ecosystem'
$map['kotlin-coroutines-flows'] = 'function-specific\language-ecosystem'
$map['kotlin-exposed-patterns'] = 'function-specific\language-ecosystem'
$map['kotlin-ktor-patterns'] = 'function-specific\language-ecosystem'
$map['kotlin-patterns'] = 'function-specific\language-ecosystem'
$map['kotlin-testing'] = 'function-specific\language-ecosystem'
$map['dart-flutter-patterns'] = 'function-specific\language-ecosystem'
$map['foundation-models-on-device'] = 'function-specific\language-ecosystem'
$map['fsharp-testing'] = 'function-specific\language-ecosystem'
$map['perl-patterns'] = 'function-specific\language-ecosystem'
$map['perl-testing'] = 'function-specific\language-ecosystem'

$skills = Get-ChildItem -LiteralPath $src -Directory | Where-Object { $_.Name -notmatch '^(platform-specific|function-specific|framework-specific|project-specific)$' }
$moved = 0; $skipped = 0; $missing = 0; $log = @()

foreach ($skill in $skills) {
  $name = $skill.Name
  $destRel = $map[$name]
  if (-not $destRel) {
    $destRel = 'function-specific\misc'
    $missing++
  }
  $destDir = Join-Path $root (Join-Path $SkillsDir $destRel)
  $target = Join-Path $destDir $name
  if ($skill.FullName -eq $target) { $skipped++; continue }
  New-Item -ItemType Directory -Force -Path $destDir | Out-Null
  Move-Item -LiteralPath $skill.FullName -Destination $target -Force
  $log += "MOVED $name -> $destRel"
  $moved++
}

$log | ForEach-Object { Write-Host $_ }
Write-Host ("Complete. moved={0} skipped={1} missing_fallback={2}" -f $moved,$skipped,$missing)
